HELP_DETAILS = {
    "helpmaya": "Lists all commands or shows details for one command.",
    "teamstats": "Uses the hardcoded FOOTBALL_TEAMS list.",
    "rolecount": "Role name is case-sensitive; use quotes for spaces.",
    "allroles": "Shows top 25 roles by member count.",
    "multirolecount": "Pass multiple role names in quotes.",
    "rolesearch": "Keyword match is case-insensitive.",
    "myteam": "Looks at your team roles across supported leagues.",
    "fixtures": "Use match IDs from this list for predictions.",
    "predict": "Pick home/away/draw (outcome only) for any match ID.",
    "mypicks": "Shows your saved picks and match status.",
    "leaderboard": "Scores only finished matches (2 pts per correct outcome).",
    "results": "Shows latest matchweek results and fixtures.",
    "join": "Bot joins whichever voice channel you're currently in.",
    "leave": "Bot disconnects from the voice channel.",
    "hi_maya": "Say hi and Maya will greet you back.",
    "whatsup_maya": "Maya flirts with you and spills some server gossip.",
    "allabout": "Get all facts about a mentioned user. Usage: !allabout @user",
    "fact": "Get a single random fact about a mentioned user. Usage: !fact @user",
    "flirtwith": "Maya flirts with the mentioned user. Usage: !flirtwith @user",
}

HELP_EXAMPLES = {
    "rolecount": "!rolecount \"Man United\"",
    "multirolecount": "!multirolecount \"Man United\" \"Barcelona\"",
    "rolesearch": "!rolesearch united",
    "myteam": "!myteam",
    "fixtures": "!fixtures\n!fixtures laliga",
    "predict": "!predict 538007 home",
    "mypicks": "!mypicks",
    "leaderboard": "!leaderboard",
    "results": "!results\n!results laliga 5",
}
